theme: jekyll-theme-minimal
title: "Infinity Family"
description: "Pursuing the World for Everyone. [video](https://github.com/infamily/infamily.github.io/blob/master/assets/media/infty.mp4?raw=true)"
show_downloads: false
